name: Sync Trello Card

on:
  issue_comment:
    types: [created, edited]
    
jobs:
  snyc-trello-card:
    name: Sync Trello Card
    if: contains(github.event.comment.body, 'trello.com/c/') 
    runs-on: ubuntu-latest
  steps:
      - name: Extract Trello Card ID
        id: extract_id
        run: echo ${{ github.event.comment.body }}
