name: Sync Trello Card

on:
  issue_comment:
    types: [created, edited]
    
jobs:
  snapshot:
    name: Sync Trello Card
    # if: contains(github.event.comment.body, 'trello.com/c/') 
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: echo "a comment"
      - name: Add initial reaction
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            COMMENT_ID: ${{ github.event.comment.id }}
            REACTION_TYPE: 'eyes'
        run: |
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/issues/comments/$COMMENT_ID/reactions \
              -d '{"content":"'$REACTION_TYPE'"}'
        