name: Sync Trello Card

on:
  issue_comment:
    types: [created, edited]
    
jobs:
  snapshot:
    name: Sync Trello Card
    if: contains(github.event.comment.body, 'trello.com/c/') 
    runs-on: ubuntu-latest
    steps:
      - name: Extract Trello Card ID
        run: |
          echo "::set-output name=trello_card_id::$(echo ${{ github.event.comment.body }} | grep -oP '(?<=trello.com/c/)[^/]+')"
      - name: Log Message
        run: echo "Trello Card ID: ${{ steps.extract_id.outputs.trello_card_id }}"