name: Sync Trello Card

on:
  issue_comment:
    types: [created, edited]
    
jobs:
  snapshot:
    name: Sync Trello Card
    if: contains(github.event.comment.body, 'trello.com/c/') 
    runs-on: ubuntu-latest
    steps:
      - name: Log Message
        run: echo "a comment"
      - name: Add initial reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: eyes