name: Sync Trello Card

on:
  issue_comment:
    types: [created, edited]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Extract Trello Card ID
      id: extract_id
      run: |
        echo "Trello Card URL: ${{ github.event.comment.body }}"
        trello_url="${{ github.event.comment.body }}"
        trello_card_id="${trello_url#*trello.com/c/}"
        echo "Trello Card ID: ${{ env.TRELLO_CARD_ID := ${trello_card_id%%/*} }}"
    - name: Use the Trello Card ID
      run: echo "Trello Card ID: ${{ env.TRELLO_CARD_ID }}"
      
